export const REQUEST_ERROR = "REQUEST_ERROR";
export const HIDE_REQUEST_ERROR = "HIDE_REQUEST_ERROR";

export const REGISTER_START = "REGISTER_START";
export const REGISTER_SUCCESS = "REGISTER_SUCCES";
