export const REQUEST_INIT = "REQUEST_INIT";
export const REQUEST_ERROR = "REQUEST_ERROR";
export const HIDE_REQUEST_ERROR = "HIDE_REQUEST_ERROR";
export const REQUEST_SUCCESS = "REQUEST_SUCCES";
export const HIDE_REQUEST_SUCCESS = "HIDE_REQUEST_SUCCESS";

export const REGISTER_START = "REGISTER_START";
export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
