export const REQUEST_INIT = "REQUEST_INIT";
export const REQUEST_ERROR = "REQUEST_ERROR";
export const HIDE_REQUEST_ERROR = "HIDE_REQUEST_ERROR";
export const REQUEST_SUCCESS = "REQUEST_SUCCES";
export const HIDE_REQUEST_SUCCESS = "HIDE_REQUEST_SUCCESS";

export const REGISTER_START = "REGISTER_START";
export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_FAILED = "REGISTER_FAILED";

export const LOGIN_START = "LOGIN_START";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAILED = "LOGIN_FAILED";
export const LOGOUT = "LOGOUT";

export const EMAIL_ACTIV_START = "EMAIL_ACTIV_START";
export const EMAIL_ACTIV_SUCCESS = "EMAIL_ACTIV_SUCCESS";
export const EMAIL_ACTIV_FAILED = "EMAIL_ACTIV_FAILED";

export const RESET_AUTH_STATUS = "RESET_AUTH_STATUS";

export const FETCH_USER_PROFILE_START = "FETCH_USER_PROFILE_START";
export const FETCH_USER_PROFILE_SUCCESS = "FETCH_USER_PROFILE_SUCCESS";
export const FETCH_USER_PROFILE_FAILED = "FETCH_USER_PROFILE_FAILED";